import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import usersRouter from "./users.js";
import studentsRouter from "./students.js";
import hospitalsRouter from "./hospitals.js";
import casesRouter from "./cases.js";
import schedulesRouter from "./schedules.js";
import attendanceRouter from "./attendance.js";
import slotsRouter from "./slots.js";
import recommendationsRouter from "./recommendations.js";
import notificationsRouter from "./notifications.js";
import announcementsRouter from "./announcements.js";
import analyticsRouter from "./analytics.js";
import academicRouter from "./academic.js";
import academicSchedulesRouter from "./academic-schedules.js";
import evaluationsRouter from "./evaluations.js";
import reportsRouter from "./reports.js";
import dutyVerificationsRouter from "./duty-verifications.js";
import academicYearSettingsRouter from "./academic-year-settings.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(studentsRouter);
router.use(hospitalsRouter);
router.use(casesRouter);
router.use(schedulesRouter);
router.use(attendanceRouter);
router.use(slotsRouter);
router.use(recommendationsRouter);
router.use(notificationsRouter);
router.use(announcementsRouter);
router.use(analyticsRouter);
router.use(academicRouter);
router.use(academicSchedulesRouter);
router.use(evaluationsRouter);
router.use(reportsRouter);
router.use(dutyVerificationsRouter);
router.use(academicYearSettingsRouter);

export default router;
